### ISSUE TITLE
Help me to solve this i Got error code: 'ERR_DLOPEN_FAILED'

### ISSUE THREAD

**Issue by devsanthoshmk** [deadlyjack/acode-plugin#36]
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js
- /data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/index.js
- /data/data/com.termux/files/usr/lib/node_modules/acodex-server/terminalServer.js
- /data/data/com.termux/files/usr/lib/node_modules/acodex-server/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js',
    '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/index.js',
    '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/terminalServer.js',
    '/data/data/com.termux/files/usr/lib/node_modules/acodex-server/index.js'
  ]
}
/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js:40
        throw outerError;
        ^

Error: dlopen failed: cannot locate symbol "_ZN2v812api_internal18GlobalizeReferenceEPNS_8internal7IsolateEPm" referenced by "/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/build/Release/pty.node"...
    at Module._extensions..node (node:internal/modules/cjs/loader:1475:18)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/acodex-server/node_modules/node-pty/lib/unixTerminal.js:29:11)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v21.6.2

**Comment by yucho123987** [comment]
Use Termux directly instead of AcodeX

**Comment by devsanthoshmk** [comment]
> Use Termux directly instead of AcodeX

Bruh using acode is a better option na.. instead of switching apps and trying to maintain paths in both which leads to error and waste of time la...

And now the issue is resolved and it works fine now
